name: jenkins-maven-cd
description: Deploys a Maven project to the Jenkins Artifactory repository in continuous delivery style.
inputs:
  GITHUB_TOKEN:
    required: true
  MAVEN_USERNAME:
    required: true
  MAVEN_TOKEN:
    required: true
runs:
  using: composite
  steps: 
    - run: GITHUB_TOKEN=${{ inputs.GITHUB_TOKEN }} MAVEN_USERNAME=${{ inputs.MAVEN_USERNAME }} MAVEN_TOKEN=${{ inputs.MAVEN_TOKEN }} $GITHUB_ACTION_PATH/run.sh
      shell: bash
